# permissions for end users to edit dbaasinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaasinventory-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasinventories/status
  verbs:
  - get
