# permissions for end users to edit dbaasproviderregistrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaasproviderregistration-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasproviderregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasproviderregistrations/status
  verbs:
  - get
