# permissions for end users to view dbaasinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaasinventory-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasinventories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasinventories/status
  verbs:
  - get
