
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasconnections/finalizers
  verbs:
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasconnections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasinventories/finalizers
  verbs:
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasinventories/status
  verbs:
  - get
  - patch
  - update
